### PR TITLE
Improve Data Node schema based on latest conventions

### PR DESCRIPTION
**Pull request by tschaffter**
## Improvements

- Add parameters to their own YAML file
- Use different schema for creation request and response (see https://github.com/Sage-Bionetworks/rocc-schemas/issues/44)
- Return empty 200 + `{}` object when deleting
- Return ID of newly created entity ID (may not be applicable here to stay close to Google Healthcare API)
- Invalid POST request should return 403 Forbidden instead of 404 ([reference](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1))
- Do not use 403 and Unauthorized schema, because Unauthorized is 401.

## Resources

- [x] Dataset
- [x] FHIR store
- [x] Patient store
- [x] Patient
- [x] Note store
- [x] Note
- [x] Annotation store
- [x] Note

### CODE REVIEW

**Comment by tschaffter** [comment]
The IBM Validator and openapi-cli accept an endpoint with a request body object that has no `properties:` section. However the HTML page generated by redocli is not very intuitive as shown below.

image

**Comment by tschaffter** [comment]
## Comment on POST request and response body schema names

### Comment 1

Tower NF is used a a source of inspiration for the name of the schemas of the request body and response body of the POST request. Tower NF is not consistent in the naming of these schemas: sometimes it uses the format illustrated by "TraceCreateRequest" and sometimes the format illustrated by "CreateAccessTokenResponse".

I propose to adopt the format "XCreateRequest" and "XCreateResponse" schemas so that they are listed in an IDE close to other "X" schemas.

### Comment 2

Our `components` folder includes the subfolders `schemas`, `parameters`, `responses`, `headers` and `securitySchemes`. The folder `responses` in particular defines full response object, currently only for errors. Here is an example of response object.

```
description: Invalid request
content:
  application/json:
    schema:
      $ref: ../schemas/Error.yaml
```

I was initially against naming schemas that ends with the prefix "Response" as one may expect the YAML file to include a response object similar to the one shown above. A more descriptive name could have been to name the object `ResponseBody` and by association `RequestBody`. However, `requestBody` is a standard openapi term as shown below and we end up with the same issue that pushed us toward this solution.

```
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/DatasetCreateRequest.yaml
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ../components/schemas/DatasetCreateResponse.yaml
      description: Success
```

To make it simple, I propose to simply name the schemas with the suffix "Response" and "Request" as done by Tower NF. The fact that these YAML files are located in the folder `schemas` should be a sufficient to inform the user of the format of their content.

**Comment by thomasyu888** [comment]
I stood up the new data node locally, and have been playing with the new client.  Everything works essentially the same except there is a tiny not as smooth affect.  Lets take example in creating and getting dataset

```python
import datanode
host="0.0.0.0:8080/api/v1"
configuration = datanode.Configuration(host=host)
with datanode.ApiClient(configuration) as api_client:
    dataset_api = datanode.DatasetApi(api_client)
    dataset = dataset_api.get_dataset("awesome-dataset")

    new_dataset = dataset_api.create_dataset("new-dataset", body={})

type(dataset)
datanode.models.dataset.Dataset
type(new_dataset)
datanode.models.dataset_create_response.DatasetCreateResponse
```

**Comment by tschaffter** [comment]
> So, creation of something will return {resource}CreateResponse but getting a resource will return {resource}.

Yes, that's the behavior we have defined in the schema. This is not a problem in itself. Is the issue rather that the generator creates automatically documentation that you think may be confusing? For example, does the generator creates the variable `new_dataset`?

**Review by thomasyu888 — APPROVED** [review]

**Pull request merged**
