### PR TITLE
Create Submission API

### PR DESCRIPTION
**Pull request by tschaffter**

### CODE REVIEW

**Comment by thomasyu888** [comment]
Would the submission API controller be responsible for:

1. Creating participant project (workspace: e.g. {user}=nlp-sandbox-workspace)) or search for this project if exists
2. Building repo
3. test repo locally with downloadable data
4. push to synapse
5. Submit to challenge.

**Comment by tschaffter** [comment]
@thomasyu888 There are different use cases where this submission API could be useful:

I want to enable user to make a submission using the CLI client. Two implementation options:
1. The client sends the submission object (JSON object) directly to Synapse OR
2. The client sends the submission object to the NLP Sandbox Submission API, which is then responsible for making sure that the submission is being pushed to Synapse. This option would bring us a step closer to a submission API similar to the challenge submission API we will come up to.

Another cool feature that I would like to put in place (low priority), is to enable a GitHub ready page to place a badge that shows the status of the submission (running, passed) as a badge. This feature needs a submission API server because we can't do that using Synapse alone.

**Comment by thomasyu888** [comment]
I think 1. is currently more doable than 2.

> 1. The client sends the submission object (JSON object) directly to Synapse
This option would be nice, but there would be multiple rest calls to Synapse.  The fact of the matter is that the docker submission is a docker repository inside Synapse and an entity is submitted makes it difficult.  It would be difficult for it to just be a JSON object, but it would essentially follow the steps I outlined.

> 2 The client sends the submission object to the NLP Sandbox Submission API, which is then responsible for making sure that the submission is being pushed to Synapse. This option would bring us a step closer to a submission API similar to the challenge submission API we will come up to.
One issue is that we currently can't submit as another user so the submission API might have to build in a "quota" system.  Another big issue is that we don't want to be involved in building people's docker containers, so this would be difficult.  If we ignore Synapse completely, a submission could just be a docker repo+shadigest, which then would make this easier concept easier (as it is just a string). Participants would be responsible for building their own images, pushing to their registry of choice and providing us with read permissions.

**Comment by tschaffter** [comment]
The objective of this PR and more is now tracked in https://github.com/Sage-Bionetworks/submission-schemas. The comments in this PR provides insights for [this discussion](https://github.com/Sage-Bionetworks/submission-schemas/issues/1).

**Pull request closed without merging**
